[global]

screenwidth = 2048
screenheight = 1024

[physics]

simtype = "barnes-hut"      # simtypes: classical or barnes-hut
threshold = 1.0

[[galaxy]]
posx = 0.0
posy = 0.0
velx = 0.0
vely = 0.0
radius = 700.0
nstars = 5000
shape = "random"             #random or concentric
kinetics = "circular"             #zero, random, circular
centralmass = 500.0
othermass = 1.0
