[display]

screenwidth = 2560
screenheight = 1440

[physics]

simtype = "barnes-hut-parallel"      # simtypes: classical, barnes-hut, barnes-hut-parallel
threshold = 1.0
dt = 0.05

[[galaxy]]
posx = 0.0
posy = 0.0
velx = 0.0
vely = 0.0
radius = 500.0
nbody = 5000
shape = "random-even"             #random-even, random-weighted or concentric
kinetics = "circular"             #zero, random, circular
centralmass = 1000.0
othermass = 1.0
